services: 
  mysqldb:
    restart: on-failure
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - app_net
    volumes:
      - mysql-vol:/var/lib/mysql
      - ./database/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

networks:
  app_net:
    driver: bridge

volumes:
  mysql-vol: