DROP TABLE IF EXISTS CANAL;
DROP TABLE IF EXISTS VIDEO;
DROP TABLE IF EXISTS CLASIFICACION;
DROP TABLE IF EXISTS FAVORITO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS SUSCRIPCION;

CREATE TABLE USUARIO (
     USU_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
     SUSCRIPCION_SUS_ID BIGINT UNSIGNED NOT NULL,
     NOMBRE TEXT NOT NULL,
     CORREO TEXT NOT NULL,
     USUARIO TEXT NOT NULL,
     CONTRASENA TEXT NOT NULL,
     ROL TEXT NOT NULL,
     SEXO TEXT NOT NULL,
     FECHA_NACIMIENTO DATE NOT NULL,
     TELEFONO TEXT NOT NULL,
     PRIMARY KEY (USU_ID)
);

CREATE TABLE SUSCRIPCION (
     SUS_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
     USUARIO_USU_ID BIGINT UNSIGNED NOT NULL,
     FECHA_INICIO DATETIME NOT NULL,
     FECHA_FIN DATETIME NOT NULL,
     PRIMARY KEY (SUS_ID)
);

ALTER TABLE USUARIO ADD UNIQUE INDEX USUARIO__IDX (SUSCRIPCION_SUS_ID);

ALTER TABLE USUARIO ADD CONSTRAINT FK_SUSCRIPCION_USUARIO FOREIGN KEY (SUSCRIPCION_SUS_ID) REFERENCES SUSCRIPCION (SUS_ID) ON DELETE CASCADE;

ALTER TABLE SUSCRIPCION ADD UNIQUE INDEX SUSCRIPCION__IDX (USUARIO_USU_ID);

ALTER TABLE SUSCRIPCION ADD CONSTRAINT FK_USUARIO_SUSCRIPCION FOREIGN KEY (USUARIO_USU_ID) REFERENCES USUARIO (USU_ID) ON DELETE CASCADE;

CREATE TABLE CANAL (
     ID_CAN BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
     NOMBRE TEXT NOT NULL,
     ENLACE TEXT NOT NULL,
     RESENA TEXT NOT NULL,
     PORTADA TEXT NOT NULL,
     PRIMARY KEY (ID_CAN)
);

CREATE TABLE CLASIFICACION (
     CLA_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
     NOMBRE TEXT NOT NULL,
     PRIMARY KEY (CLA_ID)
);

CREATE TABLE VIDEO (
     VID_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
     BUCKET TEXT NOT NULL,
     KEY_NAME TEXT NOT NULL,
     FECHA DATETIME NOT NULL,
     NOMBRE TEXT NOT NULL,
     RESENA TEXT NOT NULL,
     DURACION TEXT NOT NULL,
     PORTADA TEXT NOT NULL,
     CLASIFICACION_CLA_ID BIGINT UNSIGNED NOT NULL,
     PRIMARY KEY (VID_ID),
     FOREIGN KEY (CLASIFICACION_CLA_ID) REFERENCES CLASIFICACION (CLA_ID)
);

CREATE TABLE FAVORITO (
     FAV_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
     USUARIO_USU_ID BIGINT UNSIGNED NOT NULL,
     VIDEO_VID_ID BIGINT UNSIGNED NOT NULL,
     PRIMARY KEY (FAV_ID),
     FOREIGN KEY (USUARIO_USU_ID) REFERENCES USUARIO (USU_ID),
     FOREIGN KEY (VIDEO_VID_ID) REFERENCES VIDEO (VID_ID)
);