DROP TABLE IF EXISTS CANAL;

DROP TABLE IF EXISTS VIDEO;

DROP TABLE IF EXISTS CLASIFICACION;

DROP TABLE IF EXISTS FAVORITO;

DROP TABLE IF EXISTS SUSCRIPCION;

DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
USU_ID BIGINT NOT NULL AUTO_INCREMENT,
NOMBRE TEXT NOT NULL,
CORREO TEXT NOT NULL,
USUARIO VARCHAR(10) NOT NULL UNIQUE,
CONTRASENA TEXT NOT NULL,
ROL TEXT NOT NULL,
GENERO VARCHAR(1) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
TELEFONO TEXT NOT NULL,
ESTADO VARCHAR(10) NOT NULL,
PRIMARY KEY (USU_ID)
);

CREATE TABLE CANAL (
ID_CAN BIGINT NOT NULL,
NOMBRE TEXT NOT NULL,
ENLACE TEXT NOT NULL,
RESENA TEXT NOT NULL,
PORTADA TEXT NOT NULL,
PRIMARY KEY (ID_CAN)
);

CREATE TABLE CLASIFICACION (
CLA_ID BIGINT NOT NULL AUTO_INCREMENT,
NOMBRE TEXT NOT NULL,
PRIMARY KEY (CLA_ID)
);

CREATE TABLE VIDEO (
VID_ID BIGINT NOT NULL AUTO_INCREMENT,
BUCKET TEXT NOT NULL,
LLAVE TEXT NOT NULL,
FECHA DATETIME NOT NULL,
NOMBRE TEXT NOT NULL,
RESENA TEXT NOT NULL,
DURACION TEXT NOT NULL,
PORTADA TEXT NOT NULL,
CLASIFICACION_CLA_ID BIGINT NOT NULL,
PRIMARY KEY (VID_ID),
FOREIGN KEY (CLASIFICACION_CLA_ID) REFERENCES CLASIFICACION (CLA_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);


CREATE TABLE FAVORITO (
FAV_ID BIGINT NOT NULL AUTO_INCREMENT,
USUARIO_USU_ID BIGINT NOT NULL,
VIDEO_VID_ID BIGINT NOT NULL,
PRIMARY KEY (FAV_ID),
FOREIGN KEY (USUARIO_USU_ID) REFERENCES USUARIO (USU_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (VIDEO_VID_ID) REFERENCES VIDEO (VID_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE SUSCRIPCION (
SUS_ID BIGINT NOT NULL AUTO_INCREMENT,
FECHA_INICIO DATETIME NOT NULL,
FECHA_FIN DATETIME NOT NULL,
USUARIO_USU_ID BIGINT NOT NULL,
PRIMARY KEY (SUS_ID),
FOREIGN KEY (USUARIO_USU_ID) REFERENCES USUARIO (USU_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

INSERT INTO USUARIO(NOMBRE,CORREO,USUARIO,CONTRASENA,ROL,GENERO,FECHA_NACIMIENTO,TELEFONO,ESTADO) VALUES('ADMINISTRADOR', 'carlosmartz1995@gmail.com', 'admin', 'admin', 'ADMINISTRADOR','M','1995-07-20','502-4583-9132','ACTIVO');
